server:
  port: ${TEMPERATURE_STORAGE_SERVER_PORT:9000}
  servlet:
    context-path: /temperature-storage
spring:
  application:
    name: temperature-storage
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/temperature-monitor}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
kafka:
  url: ${KAFKA_URL:127.0.0.1:29092}